name: "Release"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create WOTLK package
      env:
        VERSION: ${{ github.ref_name }}
      run: |
        mkdir -p PitBull4_AuraBar_Reloaded
        cp PitBull4_AuraBar_Reloaded.lua PitBull4_AuraBar_Reloaded_Wrath.toc PitBull4_AuraBar_Reloaded
        zip -r "PitBull4_AuraBar_Reloaded_${VERSION}_Wrath.zip" PitBull4_AuraBar_Reloaded
        rm -rf PitBull4_AuraBar_Reloaded

    - name: Create Retail package
      env:
        VERSION: ${{ github.ref_name }}
      run: |
        mkdir -p PitBull4_AuraBar_Reloaded
        cp PitBull4_AuraBar_Reloaded.lua PitBull4_AuraBar_Reloaded_Mainline.toc PitBull4_AuraBar_Reloaded
        zip -r "PitBull4_AuraBar_Reloaded_${VERSION}_Retail.zip" PitBull4_AuraBar_Reloaded


    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          PitBull4_AuraBar_Reloaded_${{ github.ref_name }}_Wrath.zip
          PitBull4_AuraBar_Reloaded_${{ github.ref_name }}_Retail.zip
